# Generated by Django 4.2.30 on 2026-07-31 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(choices=[('Theft', 'Theft'), ('Robbery', 'Robbery'), ('Kidnapping', 'Kidnapping'), ('Assault', 'Assault'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crime_images/')),
                ('personnel_status', models.CharField(choices=[('Pending', 'Pending'), ('Under investigation', 'Under investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
