# Generated by Django 4.2.30 on 2026-07-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='image',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='personnel_status',
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='crime_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='date_reported',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_joined',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
